- hosts: all
  become: true
  tasks:
    - name: Navigate to directory containing docker-compose.yml
      shell: cd devops-assessment
      args:
        chdir: /home/ec2-user

    - name: Run docker-compose 
      shell: docker-compose down -d
      args:
        chdir: /home/ec2-user/devops-assessment
